name: Weekly Report
description: Weekly VIP and Team Meeting Recap
title: "Weekly Report – Week #: [e.g., Week 8]"
labels: ["weekly-report"]
body:
  - type: markdown
    attributes:
      value: |
        ### Weekly Week #: [e.g., Week 8]  
        **Dates:** [MM/DD/YY – MM/DD/YY]

        ----------------------------------------
        **VIP Meeting Recall**
        - What did you go over?
        - Team 1’s Tasks
        - Team 2’s Tasks
        - … [Customize as needed]

        ----------------------------------------
        **1. Objectives for the Week**
        - Task 1: [Main goal or task]
        - … [Customize as needed]

        ----------------------------------------
        **2. Challenges, Solutions, Accomplishments**
        - **Challenge:** [Brief description]
        - **How Addressed:** [Steps taken / ongoing approach]
        - **Status:** Solved / Ongoing Issue

        ----------------------------------------
        **3. Reflection & Next Steps**
        - **Progress Check:** [Did you meet your weekly goals?]
        - **Next Week’s Focus:** [Main priorities or tasks]
        - **Resources Needed:** [N/A if none]

        **Your Team Meeting Recall**
        - What did you go over?
        - Team Member 1’s Tasks
        - Team Member 2’s Tasks
        - … [Customize as needed]
